<?php
// Set the values to your parameters
// ONLY change text between quotes
//
// Your callsign
$CALL = "Your CALL";
//
// Your name
$NAME = "Your NAME";
//
// Your location
$LOCATION = "Your LOCATION";
//
// Second line header title
$TITLE2 = "RPi2-3 Node";
//
// Third line header title
$TITLE3 = "Allstar/IRLP/Echolink System Manager";
//
// Background image - specify path if not /var/www/html/supermon
// Leaving BACKGROUND null "" results in BACKGROUND_COLOR
$BACKGROUND = "background.jpg";
//
// Background color if no image
$BACKGROUND_COLOR = "blue";
//
// Height of background - matches image height
$BACKGROUND_HEIGHT = "124px";
// Supermon screen REFRESH delay time in seconds
// Default is 21600 seconds, six hours
$REFRESH_DELAY = "21600";
//
// Show number of core dump files that may exist, IF any
;$SHOW_COREDUMPS = "yes";
//
// Show weather conditions and temperature for Zip code area
$LOCALZIP = "33904";

?>
