#!/bin/sh

set -e

lb build noauto "${@}" 2>&1 | tee build.log

. ./scripts/functions.sh


if [ -f "$(cat config/build | grep ^Name:.*rpi | sed 's/^Name: \(.*\)$/\1/g')-armhf.img" ]; then
    PLATFORM="armhf"

    openDiskImage $PLATFORM

    if [ "${PLATFORM}" = "armhf" ]; then
        ./rpi_files/rpi_setup.sh
    fi

    ./scripts/post_build.sh

    closeDiskImage
fi
