#!/bin/bash

export BUILDVER=$(cat .version)
BUILDDATE=$(date +"%Y%m%d")
DISTRO=$(echo "${*}" | grep "\-\-distribution" | sed 's/^.*--distribution \([^ ]*\).*$/\1/g')
if [ -z $DISTRO ]; then
  DISTRO="buster"
fi
BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [ $BRANCH == "develop" ]; then
  REPO_ENV="-devel"
elif [ $BRANCH = "testing"]; then
  REPO_ENV="-testing"
else
  REPO_ENV=""
fi

OPTIONS=()

if [[ " ${@} " =~ " build_rpi " ]]; then
  OPTIONS+=(
    --architectures armhf 
    --image-name asl-${BUILDVER}-${BUILDDATE}-${DISTRO}-rpi
    --binary-images hdd 
    --binary-filesystem ext4 
    --hdd-size 4096
    --hdd-partition-start 512MB 
    --bootappend-live "boot=live config hostname=repeater username=repeater"
    --chroot-filesystem none 
    --firmware-binary false 
    --firmware-chroot false 
    --linux-flavours rpi 
    --mirror-bootstrap "http://raspbian.raspberrypi.org/raspbian/" 
    --mirror-binary "http://raspbian.raspberrypi.org/raspbian/" 
    --linux-packages none 
    --debootstrap-options "--keyring ./raspbian-archive-keyring.gpg  --include=ca-certificates"
    --archive-areas "main contrib non-free rpi"
    --system normal 
    --updates false 
    --security false)

  PLATFORM=`uname -m` 

  if [[ "${PLATFORM}" != "armv7l" ]]; then
      OPTIONS+=(
    --bootstrap-qemu-arch armhf 
    --bootstrap-qemu-static /usr/bin/qemu-arm-static 
    )
  fi

  cp -a rpi_files/archives/* config/archives
  cp -a rpi_files/package-lists/* config/package-lists

  (cat | tee config/archives/archive.raspbian.list.chroot config/archives/archive.raspbian.list.binary) << EOF
deb http://archive.raspberrypi.org/debian/ $DISTRO main
EOF
  (cat | tee config/archives/azlux.list.chroot config/archives/azlux.list.binary) << EOF
deb http://packages.azlux.fr/debian/ $DISTRO main
EOF

curl -L http://raspbian.raspberrypi.org/raspbian/pool/main/r/raspbian-archive-keyring/raspbian-archive-keyring_20120528.2_all.deb | dpkg --fsys-tarfile - | tar xOf - ./usr/share/keyrings/raspbian-archive-keyring.gpg > raspbian-archive-keyring.gpg

else
    OPTIONS+=(
    --architectures amd64
    --image-name asl-${BUILDVER}-${BUILDDATE}-${DISTRO}
    --debootstrap-options "--include=ca-certificates"
    --binary-images iso-hybrid
    --iso-application AllStarLink
    --iso-publisher "AllStarLink, Inc."
    --iso-volume "ASL-${BUILDVER}"
    --debian-installer live
    --debian-installer-gui false
    --archive-areas "main contrib non-free"
    --win32-loader "false"
    --security true )
for f in `ls rpi_files/archives/`; do
  rm config/archives/$f 2>/dev/null
done
for f in `ls rpi_files/package-lists`; do
  echo $f
  rm config/package-lists/$f 2>/dev/null
done
fi

# check for qemu-static

echo $BUILDVER > config/includes.chroot/etc/asl_version

(cat | tee config/archives/allstar.list.chroot config/archives/allstar.list.binary) << EOF
deb http://apt.allstarlink.org/repos/asl_builds$REPO_ENV $DISTRO main
EOF

lb config noauto --mode debian --distribution $DISTRO \
    "${OPTIONS[@]}"
