#!/bin/sh
### BEGIN INIT INFO
# Provides:          check_for_wpa_supplicant
# Required-Start:
# Required-Stop:
# Default-Start: 3
# Default-Stop:
# Short-Description: Checks /boot for wpa_supplicant.conf
# Description:
### END INIT INFO
. /lib/lsb/init-functions
case "$1" in
  start)
    log_daemon_msg "Starting check_for_wpa_supplicant"
    if [[ -f "/boot/wpa_supplicant.conf" ]]; then
        mv /boot/wpa_supplicant.conf /etc/wpa_supplicant
    fi
    log_end_msg $?
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac
