#!/bin/bash
#
# get_temp
# for Supermon 6+
# Paul Aidukas KN2R (Copyright) July 2018
# For ham radio use only, NOT for commercial use!
#
# 2/Jul/2018  Paul/KN2R    Initial release.
# 9/Nov/2018  Doug/WA3DSP  Added time stamp.
#
##################################################

echo -n "CPU: "
CTEMP=`cat /sys/class/thermal/thermal_zone0/temp`
CTEMP=`expr $CTEMP / 1000`
if [ "$CTEMP" -lt "50" ]; then
    echo -en "<span style=\"background-color: palegreen;\">"
 elif [ "$CTEMP" -lt "60" ]; then
    echo -en "<span style=\"background-color: yellow;\">"
 else
    echo -en "<span style=\"font-weight: bold; color: yellow; background-color: red;\">"
fi
FTEMP=`expr 9 '*' $CTEMP / 5 + 32`
echo -en "&nbsp;${FTEMP}&deg;F, ${CTEMP}&deg;C </span>&nbsp; @ `date +%H:%M`&nbsp;"

