#!/bin/bash
#
# Paul Aidukas KN2R (Copyright) 29-Feb-2017
# Update EchoLink database for SuperMon.
# For ham radio use only, NOT for commercial use!
#
# 29-Feb-2017 Paul/KN2R initial release.
# 05-Feb-2018 David/KB4FXC many changes.
#
#################################################

PID=$$
IRLP_DB=/tmp/irlpdata.txt.gz

# IRLP database:
if [ -e /etc/asterisk/irlp.conf ]; then
	 wget -O- -q http://status.irlp.net/nohtmlstatus.txt.bz2 | bzcat | sed 's/\t/|/g' | gzip > ${IRLP_DB}
	LEN=$(zcat ${IRLP_DB} | wc -l | awk '{print $1}')
	if [ $LEN -gt 100 ] ; then
		echo LENGTH = $LEN
		echo "File 'IRLP database' updated."
	else
		rm -f "${IRLP_DB}"
	fi
else
	echo "IRLP is not configured, aborting."
fi

