#!/bin/bash
#
# Author: Paul Aidukas/KN2R (Copyright) Jan 3, 2015
# IRLP lookup for Allstar Monitor
# For ham radio use only, NOT for commercial use!
#
# 01-03-2015  Paul/KN2R  Initial release.
#
#####################################################

VUTIL_CALLS=/var/log/irlp/vutil_calls
EXP_X_REF=/home/irlp/scripts/exp-x-reference


Arg=$(echo "$1")

if [ -z "$Arg" ]; then
   echo -e "\nNo Node # supplied.\n\a"
   exit
fi

if [ $Arg -gt 9999 ]; then
   Arg=$(echo $Arg |cut -c 2-)
fi

if [ $Arg -lt 1000 ]; then
   Ans1="EXP${Arg} IRLP "$(cat $EXP_X_REF |grep -e ^"exp${Arg}" |head -1 |cut -d ":" -f 2,5-6 |sed 's/\:/ /g')
   Ans="$Ans1"
elif [ $Arg -ge 9000 ]; then
   Arg2=$(echo $Arg |cut -c 1-3)0
   Ans1=$(cat $VUTIL_CALLS |grep -e ^"$Arg2" |head -1 |cut -d "," -f2)
   Ans2=$(cat $VUTIL_CALLS |grep -e ^"$Arg2" |head -1 |cut -d "~" -f3-5 |sed 's/\~/, /g')
   Ans="$Ans1 [IRLP $Arg] $Ans2"
else
   Ans1=$(cat $VUTIL_CALLS |grep -e ^"$Arg" |head -1 |cut -d "," -f2)
   Ans2=$(cat $VUTIL_CALLS |grep -e ^"$Arg" |head -1 |cut -d "~" -f3-5 |sed 's/\~/, /g')
   Ans="$Ans1 [IRLP $Arg] $Ans2"
fi

if [ $Arg -ge 9990 ]; then
   Ans1="REF"$Arg
   Ans="$Ans1 [IRLP ECHO Reflector $Arg]"
fi

if [ -z "$Ans1" ]; then
   if [ $Arg -ge 9000 ]; then
      Ans1="REF"$Arg
      Ans="$Ans1 [IRLP Reflector $Arg]"
    else
      Arg=$(echo $Arg |tr '[:lower:]' '[:upper:]')
      # Ans="No-Info... [IRLP $Arg]"
      Ans="No-Info... [IRLP # ??]"
   fi
fi

[ -n "$Arg2" ] && Ans=$(echo "$Ans" |sed 's/REF'$Arg2'/REF'$Arg'/g')

echo "$Ans"

