name: make_image
run-name: Make ASL Image (${{ github.ref_name }}) for ${{ inputs.target }}
on: 
  workflow_dispatch:
    inputs:
      target:
        type: choice
        options: 
        - pc
        - pi
jobs:
  make-images:
    uses: AllStarLink/asl_workflows/.github/workflows/ephemeral_ec2_run-this.yml@develop
    with:
      run-this: ./docker/dockerbuild.sh -t ${{ inputs.target }}
      arch: ${{ inputs.target == 'pc' && 'x86_64' || inputs.target == 'pi' && 'x86_64' || null }}
      artifact-path: 'asl-*.*'
    secrets: inherit
